package com.rp.hd.domain;

public enum TipoMaoObra {
	CORTE_PAPEL_INTERNO,
	DOBRAGEM_ENVELOPE,
	COLAGEM_ENVELOPE,
	CORTE_RENDA,
	COLOCACAO_RENDA,
	CORTE_FITA,
	COLOCACAO_FITA_CONTORNO,
	COLOCACAO_LACO,
	ENCARTE,
	COLOCACAO_PEROLA,
	IMPRESSAO_INTERNO,
	IMPRESSAO_ENVELOPE,
	IMPRESSAO_NOME_CONVIDADOS,
	COLOCAO_NOMES_CONVIDADOS,
	COLOCACAO_SACO_PLASTICO,
	COLOCACAO_IMA,
	COLOCAO_REVESTIMENTO_INTERNO,
	CONFECCAO_LACO,
	COLOCACAO_ETIQUETA,
	SEPARACAO_SERIGRAFIA,
	SEPARACAO_PAPEL_PARA_CORTE
}
